# Site settings
title: Danilo Vaz
subtitle: "Show me your code, to tell you who you are"
email: danilo@canarinho.co
description: "amateur writer, web developer in Focusnetworks, co-founder in Canarinho and in love with Mariana Gimenes :)"
baseurl: ""
url: "http://danilovaz.github.io"
twitter_username: "maskotex"
github_username:  "danilovaz"
instagram_username: "vazdanilo"

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed