# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://danilovaz.github.io" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Danilo Vaz
  avatar: avatar.jpg
  gravatar: # email md5 hash
  description: "Oi, eu sou Danilo Vaz. Um desenvolvedor caipira de Cunha que mora em São José dos Campos. Também trabalho em uma empresa maravilhosa que tem mesa de bilhar." # used by search engines

  # Header and footer text
  header_text: >
     <p>Oi, eu sou Danilo Vaz.</p>

     <p>Um desenvolvedor caipira de Cunha que mora em São José dos campos.</p>
     <p>Também trabalho em uma empresa maravilhosa que tem mesa de bilhar.</p>
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: false
  email_address: "danilo@canarinho.co"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "danilovaz"
  google_plus:
  instagram:
  linkedin:  "http://br.linkedin.com/in/danilovaz"
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # full URL
  steam:
  tumblr:
  twitter: "_danilovaz"
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-53501202-1" # tracking id, e.g. "UA-000000-01"
  disqus_shortname:

  # Localization strings
  str_follow_on: "Siga no"
  str_rss_follow: "Siga RSS feed"
  str_email: "Email"
  str_next: "Próximo"
  str_prev: "Anterior"
  str_continue_reading: "Continue lendo"

  # Colors, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
