# Site settings
title: Danilo Vaz - FrontEnd Developer
description: "A blog about HTML, CSS, JavaScript, Ember.js, Progressive Web Apps"
baseurl: "" # for test: remove string '/space-jekyll-templa' to ''
url: "https://danilovaz.github.io" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.githu.io'
# User settings
username: Danilo Vaz
user_title: Danilo Vaz - FrontEnd Developer
email: danilovaz@hotmail.com.br
twitter_username: _danilovaz
github_username:  danilovaz
gplus_username:  +DaniloVaz1993
disqus_username: danilovaz
profile_picture: https://pbs.twimg.com/profile_images/862645200291860482/Vf8EQmHn_400x400.jpg

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: home
    url: /
  - title: my posts
    url: /posts
  - title: my talks
    url: /talks
  - title: series
    url: /series
  - title: tags
    url: /tags
  - title: about me
    url: /about
  - title: what I'm doing now
    url: /doing
# talks
talks:
  - title: 'Ember.js: passado, presente e futuro'
    url: 'https://danilovaz.github.io'
# projects in header index
#projects:
  #- name: asciilang
    #url: https://github.com/victorvoid/asciilang
  #- name: vim-frontend
    #url: https://github.com/victorvoid/vim-frontend
  #- name: generator-capybara
    #url: https://github.com/victorvoid/generator-capybara
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
